### ISSUE TITLE
add rsyslog to the image?

### ISSUE THREAD

**Issue by philippfrenzel** [phundament/docker-images#2]
Hi,

would it be possible to add the rsyslog to the image? I tried adding it later during my local file:
# add cron management to the container
# RUN apt-get -y update

RUN apt-get -y install \
      rsyslog \
   --no-install-recommends && \
   apt-get clean && \
   npm -g install npm@latest && \
   rm -rf /var/lib/apt/lists/\* /tmp/\* /var/tmp/*
ADD crontab /app/crontab
RUN crontab /app/crontab
ADD crontab/bin/start-cron.sh /usr/bin/start-cron.sh
RUN chmod +x /usr/bin/start-cron.sh
RUN touch /var/log/cron.log

**Comment by schmunk42** [comment]
Did you try that? I was trying to work with cron once in a Docker container, without much success.

Or would you run it like in https://github.com/aptible/docker-cron-example as a separate container?

**Comment by philippfrenzel** [comment]
Hi, I tried both, but sadly it's not working in both ways ... :/ I get the container up an running in a separate docker container, but I still can't run any php yii console commands....

**Comment by schmunk42** [comment]
From which image are you creating the new container? Are you seeing the app? Can you show the error output?

**Comment by philippfrenzel** [comment]
```
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                            NAMES
fd8ea8004bfd        phundament/nginx-one:1.9       "/root/run.sh"           9 hours ago         Up 13 minutes       443/tcp, 0.0.0.0:40080->80/tcp   phmystorage_nginx_1
a930ee3c26e0        hamiltont/docker-cron:latest   "devcron.py /cron/cro"   9 hours ago         Up 13 minutes                                        phmystorage_cron_1
66c7cdc5938d        local/phd/app:phmystorage      "/root/run.sh"           9 hours ago         Up 13 minutes       9000/tcp                         phmystorage_php_1
ff49227d8556        percona:5.6                    "docker-entrypoint.sh"   9 hours ago         Up 13 minutes       0.0.0.0:3306->3306/tcp           phmystorage_db_1
```

And the cron container can't execute yii console as it throws a db error:/

**Comment by schmunk42** [comment]
I know it's not 100% docker, ... but can't or won't you use your hosts crontab with `docker-compose exec`?

**Comment by schmunk42** [comment]
Another option would be to install cron into your PHP image and run a separate service, like

```
cron:
  extends:
    - php
  command: cron
```

This service could extend `php` (please see the docs for the exact syntax) to have a link, network, ENV variables available, but instead of fpm it simply runs cron...

**Comment by philippfrenzel** [comment]
tried it, but never got it to run - problem was to start the cron task

:( 

within the entry script it wasn’t started correct...

**Comment by schmunk42** [comment]
For running multiple processes (which is **not** "pure Docker doctrine") in a container, have a look at the [nginx flavour](https://github.com/dmstr/docker-php-yii2/tree/master/nginx) or our latest PHP base images.

Closing, since it's not in the scope of this template project.
